version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: America/Edmonton
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.4.0
    - 7.5.0
    - 7.6.0
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
    - 4.5.9
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - 4.5.11
    - 4.5.9
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
    - 4.5.9
  - dependency-name: vue-router
    versions:
    - 3.4.9
